{
  "_from": "axios-error@^0.7.11",
  "_id": "axios-error@0.7.11",
  "_inBundle": false,
  "_integrity": "sha512-Oq7HbcAIabBcanV8qu950ZiyszlrXvKyMdYKOWveet6Vzy9ey1moyT8asWyTSlKJ5DYG4nEPMirdhxfUw/Dp7w==",
  "_location": "/axios-error",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "axios-error@^0.7.11",
    "name": "axios-error",
    "escapedName": "axios-error",
    "rawSpec": "^0.7.11",
    "saveSpec": null,
    "fetchSpec": "^0.7.11"
  },
  "_requiredBy": [
    "/messaging-api-viber"
  ],
  "_resolved": "https://registry.npmjs.org/axios-error/-/axios-error-0.7.11.tgz",
  "_shasum": "b4fb2ee20491146e6aaa23bcf29e92ca933a9b68",
  "_spec": "axios-error@^0.7.11",
  "_where": "C:\\website\\viber_bot\\npm-vber\\node_modules\\messaging-api-viber",
  "bugs": {
    "url": "https://github.com/Yoctol/messaging-apis/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "An axios error wrapper that aim to provide clear error message to the user",
  "devDependencies": {
    "axios": "^0.18.0",
    "axios-mock-adapter": "^1.15.0"
  },
  "engines": {
    "node": ">=6"
  },
  "gitHead": "8e43618226e9c46216372b813d24cae3bdf9ed9e",
  "homepage": "https://github.com/Yoctol/messaging-apis#readme",
  "keywords": [
    "axios",
    "http",
    "error"
  ],
  "license": "MIT",
  "main": "lib/index.js",
  "name": "axios-error",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Yoctol/messaging-apis.git"
  },
  "version": "0.7.11"
}
